name: ods10
description: Um caminho simplificado para a retificação de documentos para pessoas trans.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^4.5.0
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  dio: ^4.0.6
  google_fonts: 2.2.0
  percent_indicator: ^4.0.0
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.20
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7
  flutter_native_splash: ^2.1.6
  # flutter_app_name: ^0.1.0
  flutter_launcher_icons: "^0.9.2"

flutter_native_splash:
  color: "#4435AC"
  image: "assets/images/splash2.png"
  android: true
  ios: false
  android_gravity: center

# flutter_app_name:
#   name: "re.tifica"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launch_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/tutorial/
    - assets/images/laerte/
    - assets/images/xica/
